### ISSUE TITLE
Use association proxies for these

### ISSUE THREAD

**Issue by dummied** [sbaughman/breddit#8]
https://github.com/sbaughman/breddit/blob/master/app/controllers/users_controller.rb#L25
https://github.com/sbaughman/breddit/blob/master/app/controllers/users_controller.rb#L26
https://github.com/sbaughman/breddit/blob/master/app/controllers/users_controller.rb#L28

Or, better yet, just load the user and call them in the view.

**Comment by sbaughman** [comment]
resolved in previous commit
